### PR TITLE
Make video skin background repeat.

### PR DESCRIPTION
**Pull request by madbook**
Eventually if we start using this more, we might want to add an option to the UI, but for now just set the default to repeat.

:eyeglasses: @Deimos

### CODE REVIEW

**Comment by Deimos** [comment]
Should probably remove the `no-repeat` from the general definition in the
line above, or does that need to stay for some reason?

**Comment by madbook** [comment]
wow.  I don't even know how I didn't see that.  Just rushing, I think :P

**Comment by madbook** [comment]
:haircut:

**Comment by Deimos** [comment]
:fish:

**Pull request closed without merging**
