### PR TITLE
Hello Ladies Promo

### PR DESCRIPTION
**Pull request by hmphry**
Removed Jansport promos, added Hello Ladies promos.

### CODE REVIEW

**Comment by bsimpson63** [comment]
Can you rebase this to the current state of https://github.com/reddit/reddit.tv/commits/master ?

**Comment by chromakode** [comment]
When you rebase, could you please normalize the author of the 2nd and 3rd commits to match the 1st?

**Comment by chromakode** [comment]
:nail_care: (Finished a review pass, thanks! Awaiting updates; https://github.com/reddit/reddit/wiki/The-Beauty-Salon)

**Comment by chromakode** [comment]
Also: could you please squash all of the initial promo changes into one commit to ease reverting?

**Comment by hmphry** [comment]
I had no idea about the video player. I guess the best course of action is to use the div#gutter-1 and div#gutter-2, but I can't seem to get them to show up. According to the CSS, should show up, alas they just won't. I broke the images up into left and right, so I'll work on that. Sorry about all the commits. I'll make more effective commits in the future. Sure thing on that rebase, also.

**Comment by chromakode** [comment]
Np! Thanks for the quick response. Send us a `:haircut:` when you're ready for further review. :)

**Comment by hmphry** [comment]
Everything the promo should be responsive now. I don't really follow on the theme_ad.css. Is that added automatically? Do you need it moved up in the css queue?

**Comment by hmphry** [comment]
I tried to send a :haircut:, but I forgot to add it in the commit. Sorry if I just spammed you with pull requests.

**Comment by chromakode** [comment]
I believe it is not necessary to include the stylesheet line:

```
<link rel="stylesheet" href="css/theme_ad.css" type="text/css" />
```

`Globals.forceTheme` https://github.com/reddit/reddit.tv/commit/f69608d24c74cfa53bb7eed74be9dcbaa6641854#L0R51 here sets the stylesheet (read `loadTheme()`): https://github.com/reddit/reddit.tv/blob/3dce57413a83e45502e455f64943a1e2fc7c906a/js/tv.js#L80

**Comment by hmphry** [comment]
I thought that was the case, but was not sure. It's been removed.

**Comment by chromakode** [comment]
Thanks for cleaning that up. When testing this locally, it looks like the banner images are wrapping due to being wider than the background image. Is this intentional?

image

**Comment by hmphry** [comment]
The first commit fixes the image wrapping issues and the second commit is for Sunday. Everything worked for me in inspector, but let me know if you have any issues you need fixed.

**Pull request closed without merging**
