### PR TITLE
iPad UI fixes, YouTube HTML5 player

### PR DESCRIPTION
**Pull request by deanputney**
Note: Commits before Jan 23rd are from [a previous pull request](https://github.com/reddit/reddit.tv/pull/81) that's already been merged into reddit/reddit.tv master. Not sure why this is happening, as these commits are already there.

Resolves issue with YouTube player appearing squished on the iPad.
Replaces YouTube Flash embeds with HTML5 iframe embeds for proper resizing.
Adds click action to header to allow touch interfaces to more easily access video list.
UI changes to iPad interface, borderless video, cleaner channel organization.

img_0001

### CODE REVIEW

**Comment by kemitche** [comment]
> Note: Commits before Jan 23rd are from a previous pull request that's already been merged into reddit/reddit.tv master. Not sure why this is happening, as these commits are already there.

It looks like some form of rebasing was done before those old commits went to master; I think you'll want to rebase your new commits on top of "clean" reddit/reddit.tv

**Comment by Deimos** [comment]
Looks good to me, nothing really significant that needs to be changed.

:fish:

**Comment by deanputney** [comment]
The problem with the extra commits showing up appeared to be that the sponsoredchannels branch wasn't merged into master before this pull request was made. I just merged that into master, rebased to the new master head and pushed that up. Is that the correct thing to do here?

**Comment by Deimos** [comment]
> Is that the correct thing to do here?

The logic of it makes sense, and it sounds like it worked out, so it was probably good.

**Comment by deanputney** [comment]
Is this ready to go? We're reviewing another change for a pull request now, so maybe we can get them both in at the same time.

**Comment by Deimos** [comment]
I gave it a fish, nothing was changed after that point, was it?

**Comment by deanputney** [comment]
No, just a rebase for organization purposes. I want to set up this other pull request, though, so I want to merge this into our fork's master and rebase the new branch. Will that affect this pull request?

**Comment by Deimos** [comment]
I'm not sure exactly how that'll come out, I'm sure we can sort it out though. The stuff here is fine to put out to the live site though, if you want to do that first to make it easier.

**Comment by rram** [comment]
Rolled out. Please ensure your git directory is in sync. If `https://github.com/reddit/reddit.tv` is `origin` then `git checkout master; git fetch origin; git reset --hard origin/master` should do the trick

**Pull request merged**
